#!/bin/bash

gsettings set org.mate.peripherals-touchpad touchpad-enabled true

echo "****************************************************"
echo "                TouchPad ACTIVADO"
echo "****************************************************"
